### ISSUE TITLE
Location of udunits2.xml doesn't match default location. 

### ISSUE THREAD

**Issue by ghost** [conda-forge/cf_units-feedstock#4]
On Windows 64xm python 3.5 at least...

This recipe places the ununits2.xml file into:
...\Library\share\udunits\udunits2.xml

but the cf_units package is looking in 
..\Share\udunits\udunits2.xml
(Not in the Library subfolder)
https://github.com/SciTools/cf_units/blob/master/cf_units/__init__.py#L383

If it would be helpful I'll submit a pull request, but I didn't want to mess up other platforms.

**Comment by ocefpaf** [comment]
> On Windows 64xm python 3.5 at least...
> This recipe places the ununits2.xml file into:
> ...\Library\share\udunits\udunits2.xml

@ColinTalbert that sounds correct. `cf_units` can [read](https://github.com/conda-forge/cf_units-feedstock/blob/master/recipe/bld.bat#L1-L4) that path from the `site.cfg`.

> but the cf_units package is looking in 
> ..\Share\udunits\udunits2.xml
> (Not in the Library subfolder)

That is the `default` value from [`config.get_option`](See https://github.com/SciTools/cf_units/blob/master/cf_units/__init__.py#L383-L386) and should not be used in the conda package b/c we set that value in the `site.cfg`. I might be missing something here.... Can you try this to help is debug this one:

``` shell
conda create -n TEST -c conda-forge cf_units
activate TEST
python -c "import cf_units; print(cf_units.config.get_option('System', 'udunits2_xml_path'))"
```

If you get something with `Library\share` itisi working. If you get `None` something is broken.

**Comment by ghost** [comment]
My apologies!  I thought I was getting the latest cf_units from conda-forge
but instead was getting version 1.1 from the IOOS channel. It is indeed
working correctly on the conda-forge channel!

Thank you for all your hard work.
--Colin

**Comment by ocefpaf** [comment]
Glad it is resolved. BTW it is important to mentioned that IOOS channel is no longer maintained. We moved everything to `conda-forge`.

**Comment by ghost** [comment]
Good to know, I'll remove it right now.

**Comment by ocefpaf** [comment]
@ColinTalbert I believe this was narrowed down to a problem in `udunits2` so we cannot do anything here. I am closing then.
